# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/michell/Projects/pynocchio/forms/go_to_page_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GoPageDialog(object):
    def setupUi(self, GoPageDialog):
        GoPageDialog.setObjectName("GoPageDialog")
        GoPageDialog.resize(283, 513)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/elementary3-icon-theme/actions/48/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GoPageDialog.setWindowIcon(icon)
        GoPageDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        GoPageDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(GoPageDialog)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(GoPageDialog)
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.vertical_layout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.vertical_layout_3.setContentsMargins(0, 0, 9, 0)
        self.vertical_layout_3.setObjectName("vertical_layout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 258, 378))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_icon = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_icon.setText("")
        self.label_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icon.setObjectName("label_icon")
        self.horizontalLayout.addWidget(self.label_icon)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.vertical_layout_3.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_num_pages = QtWidgets.QLabel(GoPageDialog)
        self.label_num_pages.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_num_pages.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_num_pages.setObjectName("label_num_pages")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_num_pages)
        self.line_edit_num_page = QtWidgets.QLineEdit(GoPageDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_edit_num_page.sizePolicy().hasHeightForWidth())
        self.line_edit_num_page.setSizePolicy(sizePolicy)
        self.line_edit_num_page.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.line_edit_num_page.setFrame(True)
        self.line_edit_num_page.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit_num_page.setReadOnly(True)
        self.line_edit_num_page.setObjectName("line_edit_num_page")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_edit_num_page)
        self.label_current_page = QtWidgets.QLabel(GoPageDialog)
        self.label_current_page.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_current_page.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_current_page.setObjectName("label_current_page")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_current_page)
        self.line_edit_current_page = QtWidgets.QLineEdit(GoPageDialog)
        self.line_edit_current_page.setAutoFillBackground(False)
        self.line_edit_current_page.setFrame(True)
        self.line_edit_current_page.setAlignment(QtCore.Qt.AlignCenter)
        self.line_edit_current_page.setReadOnly(True)
        self.line_edit_current_page.setObjectName("line_edit_current_page")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_edit_current_page)
        self.label_go_page = QtWidgets.QLabel(GoPageDialog)
        self.label_go_page.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_go_page.setObjectName("label_go_page")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_go_page)
        self.spin_box_go_page = QtWidgets.QSpinBox(GoPageDialog)
        self.spin_box_go_page.setWrapping(False)
        self.spin_box_go_page.setAlignment(QtCore.Qt.AlignCenter)
        self.spin_box_go_page.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spin_box_go_page.setAccelerated(True)
        self.spin_box_go_page.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spin_box_go_page.setSuffix("")
        self.spin_box_go_page.setPrefix("")
        self.spin_box_go_page.setMinimum(1)
        self.spin_box_go_page.setSingleStep(1)
        self.spin_box_go_page.setObjectName("spin_box_go_page")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_box_go_page)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(GoPageDialog)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GoPageDialog)
        self.buttonBox.accepted.connect(GoPageDialog.accept)
        self.buttonBox.rejected.connect(GoPageDialog.reject)
        self.spin_box_go_page.valueChanged['int'].connect(GoPageDialog.update)
        QtCore.QMetaObject.connectSlotsByName(GoPageDialog)

    def retranslateUi(self, GoPageDialog):
        _translate = QtCore.QCoreApplication.translate
        GoPageDialog.setWindowTitle(_translate("GoPageDialog", "Go to Page"))
        self.label_num_pages.setText(_translate("GoPageDialog", "Number of pages: "))
        self.label_current_page.setText(_translate("GoPageDialog", "Current page:        "))
        self.label_go_page.setText(_translate("GoPageDialog", "Go to page:           "))

from . import main_window_view_rc
