# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './forms/main_window_view.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindowView(object):
    def setupUi(self, MainWindowView):
        MainWindowView.setObjectName("MainWindowView")
        MainWindowView.resize(1048, 537)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindowView.sizePolicy().hasHeightForWidth())
        MainWindowView.setSizePolicy(sizePolicy)
        MainWindowView.setBaseSize(QtCore.QSize(0, 3))
        MainWindowView.setFocusPolicy(QtCore.Qt.WheelFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/others/pynocchio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindowView.setWindowIcon(icon)
        MainWindowView.setIconSize(QtCore.QSize(22, 22))
        MainWindowView.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindowView.setAnimated(True)
        MainWindowView.setDocumentMode(False)
        MainWindowView.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindowView.setDockNestingEnabled(False)
        MainWindowView.setUnifiedTitleAndToolBarOnMac(True)
        self.central_widget = QtWidgets.QWidget(MainWindowView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_widget.sizePolicy().hasHeightForWidth())
        self.central_widget.setSizePolicy(sizePolicy)
        self.central_widget.setAutoFillBackground(False)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.qscroll_area_viewer = QScrollAreaViewer(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qscroll_area_viewer.sizePolicy().hasHeightForWidth())
        self.qscroll_area_viewer.setSizePolicy(sizePolicy)
        self.qscroll_area_viewer.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.qscroll_area_viewer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.qscroll_area_viewer.setAutoFillBackground(False)
        self.qscroll_area_viewer.setFrameShape(QtWidgets.QFrame.HLine)
        self.qscroll_area_viewer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.qscroll_area_viewer.setLineWidth(0)
        self.qscroll_area_viewer.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.qscroll_area_viewer.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.qscroll_area_viewer.setWidgetResizable(True)
        self.qscroll_area_viewer.setAlignment(QtCore.Qt.AlignCenter)
        self.qscroll_area_viewer.setObjectName("qscroll_area_viewer")
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 1048, 454))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area_widget_contents.sizePolicy().hasHeightForWidth())
        self.scroll_area_widget_contents.setSizePolicy(sizePolicy)
        self.scroll_area_widget_contents.setAutoFillBackground(True)
        self.scroll_area_widget_contents.setStyleSheet("")
        self.scroll_area_widget_contents.setObjectName("scroll_area_widget_contents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scroll_area_widget_contents)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.scroll_area_widget_contents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMouseTracking(False)
        self.label.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(0)
        self.label.setMidLineWidth(0)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap(":/icons/pynocchio_icon.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.qscroll_area_viewer.setWidget(self.scroll_area_widget_contents)
        self.horizontalLayout.addWidget(self.qscroll_area_viewer)
        MainWindowView.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindowView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setAcceptDrops(False)
        self.menubar.setAutoFillBackground(False)
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_recent_files = QtWidgets.QMenu(self.menu_file)
        self.menu_recent_files.setEnabled(True)
        self.menu_recent_files.setTearOffEnabled(False)
        self.menu_recent_files.setSeparatorsCollapsible(False)
        self.menu_recent_files.setObjectName("menu_recent_files")
        self.menu_view = QtWidgets.QMenu(self.menubar)
        self.menu_view.setObjectName("menu_view")
        self.menu_navegation = QtWidgets.QMenu(self.menubar)
        self.menu_navegation.setAcceptDrops(False)
        self.menu_navegation.setTearOffEnabled(False)
        self.menu_navegation.setObjectName("menu_navegation")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        self.menu_settings = QtWidgets.QMenu(self.menubar)
        self.menu_settings.setObjectName("menu_settings")
        self.menu_bookmarks = QtWidgets.QMenu(self.menubar)
        self.menu_bookmarks.setTearOffEnabled(False)
        self.menu_bookmarks.setSeparatorsCollapsible(True)
        self.menu_bookmarks.setObjectName("menu_bookmarks")
        self.menu_recent_bookmarks = QtWidgets.QMenu(self.menu_bookmarks)
        self.menu_recent_bookmarks.setObjectName("menu_recent_bookmarks")
        MainWindowView.setMenuBar(self.menubar)
        self.toolbar = QtWidgets.QToolBar(MainWindowView)
        self.toolbar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar.sizePolicy().hasHeightForWidth())
        self.toolbar.setSizePolicy(sizePolicy)
        self.toolbar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.toolbar.setAcceptDrops(True)
        self.toolbar.setAutoFillBackground(False)
        self.toolbar.setMovable(False)
        self.toolbar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolbar.setFloatable(False)
        self.toolbar.setObjectName("toolbar")
        MainWindowView.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.statusbar = StatusBar(MainWindowView)
        self.statusbar.setObjectName("statusbar")
        MainWindowView.setStatusBar(self.statusbar)
        self.action_about = QtWidgets.QAction(MainWindowView)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/help-info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_about.setIcon(icon1)
        self.action_about.setObjectName("action_about")
        self.action_about_qt = QtWidgets.QAction(MainWindowView)
        self.action_about_qt.setObjectName("action_about_qt")
        self.action_exit = QtWidgets.QAction(MainWindowView)
        self.action_exit.setObjectName("action_exit")
        self.action_next_page = QtWidgets.QAction(MainWindowView)
        self.action_next_page.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/go-next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_next_page.setIcon(icon2)
        self.action_next_page.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_next_page.setVisible(True)
        self.action_next_page.setPriority(QtWidgets.QAction.HighPriority)
        self.action_next_page.setObjectName("action_next_page")
        self.action_previous_page = QtWidgets.QAction(MainWindowView)
        self.action_previous_page.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/go-previous.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_previous_page.setIcon(icon3)
        self.action_previous_page.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_previous_page.setVisible(True)
        self.action_previous_page.setObjectName("action_previous_page")
        self.action_first_page = QtWidgets.QAction(MainWindowView)
        self.action_first_page.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/go-first.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_first_page.setIcon(icon4)
        self.action_first_page.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_first_page.setObjectName("action_first_page")
        self.action_last_page = QtWidgets.QAction(MainWindowView)
        self.action_last_page.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/go-last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_last_page.setIcon(icon5)
        self.action_last_page.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_last_page.setObjectName("action_last_page")
        self.action_rotate_left = QtWidgets.QAction(MainWindowView)
        self.action_rotate_left.setCheckable(False)
        self.action_rotate_left.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/object-rotate-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_rotate_left.setIcon(icon6)
        self.action_rotate_left.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.action_rotate_left.setObjectName("action_rotate_left")
        self.action_rotate_right = QtWidgets.QAction(MainWindowView)
        self.action_rotate_right.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/object-rotate-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_rotate_right.setIcon(icon7)
        self.action_rotate_right.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.action_rotate_right.setObjectName("action_rotate_right")
        self.action_horizontal_fit = QtWidgets.QAction(MainWindowView)
        self.action_horizontal_fit.setCheckable(True)
        self.action_horizontal_fit.setChecked(False)
        self.action_horizontal_fit.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/horizontal-fit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_horizontal_fit.setIcon(icon8)
        self.action_horizontal_fit.setVisible(True)
        self.action_horizontal_fit.setObjectName("action_horizontal_fit")
        self.action_fullscreen = QtWidgets.QAction(MainWindowView)
        self.action_fullscreen.setCheckable(False)
        self.action_fullscreen.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/fullscreen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_fullscreen.setIcon(icon9)
        self.action_fullscreen.setShortcutContext(QtCore.Qt.WidgetShortcut)
        self.action_fullscreen.setIconVisibleInMenu(True)
        self.action_fullscreen.setObjectName("action_fullscreen")
        self.action_go_to_page = QtWidgets.QAction(MainWindowView)
        self.action_go_to_page.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/edit-find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_go_to_page.setIcon(icon10)
        self.action_go_to_page.setObjectName("action_go_to_page")
        self.action_original_fit = QtWidgets.QAction(MainWindowView)
        self.action_original_fit.setCheckable(True)
        self.action_original_fit.setChecked(True)
        self.action_original_fit.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/original-fit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_original_fit.setIcon(icon11)
        self.action_original_fit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.action_original_fit.setVisible(True)
        self.action_original_fit.setObjectName("action_original_fit")
        self.action_show_statusbar = QtWidgets.QAction(MainWindowView)
        self.action_show_statusbar.setCheckable(True)
        self.action_show_statusbar.setChecked(True)
        self.action_show_statusbar.setObjectName("action_show_statusbar")
        self.action_add_bookmark = QtWidgets.QAction(MainWindowView)
        self.action_add_bookmark.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/bookmark-new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_add_bookmark.setIcon(icon12)
        self.action_add_bookmark.setVisible(True)
        self.action_add_bookmark.setObjectName("action_add_bookmark")
        self.action_remove_bookmark = QtWidgets.QAction(MainWindowView)
        self.action_remove_bookmark.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_remove_bookmark.setIcon(icon13)
        self.action_remove_bookmark.setVisible(False)
        self.action_remove_bookmark.setIconVisibleInMenu(True)
        self.action_remove_bookmark.setObjectName("action_remove_bookmark")
        self.action_bookmark_manager = QtWidgets.QAction(MainWindowView)
        self.action_bookmark_manager.setEnabled(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/system-file-manager2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_bookmark_manager.setIcon(icon14)
        self.action_bookmark_manager.setObjectName("action_bookmark_manager")
        self.action_open_folder = QtWidgets.QAction(MainWindowView)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/document-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open_folder.setIcon(icon15)
        self.action_open_folder.setVisible(True)
        self.action_open_folder.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.action_open_folder.setIconVisibleInMenu(True)
        self.action_open_folder.setObjectName("action_open_folder")
        self.action_next_comic = QtWidgets.QAction(MainWindowView)
        self.action_next_comic.setEnabled(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/media-skip-forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_next_comic.setIcon(icon16)
        self.action_next_comic.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_next_comic.setObjectName("action_next_comic")
        self.action_previous_comic = QtWidgets.QAction(MainWindowView)
        self.action_previous_comic.setEnabled(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/media-skip-backward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_previous_comic.setIcon(icon17)
        self.action_previous_comic.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_previous_comic.setObjectName("action_previous_comic")
        self.action_preference_dialog = QtWidgets.QAction(MainWindowView)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/elementary3-icon-theme/actions/48/document-properties.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_preference_dialog.setIcon(icon18)
        self.action_preference_dialog.setVisible(False)
        self.action_preference_dialog.setObjectName("action_preference_dialog")
        self.action_vertical_fit = QtWidgets.QAction(MainWindowView)
        self.action_vertical_fit.setCheckable(True)
        self.action_vertical_fit.setChecked(False)
        self.action_vertical_fit.setEnabled(False)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/icons/vertical-fit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_vertical_fit.setIcon(icon19)
        self.action_vertical_fit.setAutoRepeat(True)
        self.action_vertical_fit.setVisible(True)
        self.action_vertical_fit.setObjectName("action_vertical_fit")
        self.action_best_fit = QtWidgets.QAction(MainWindowView)
        self.action_best_fit.setCheckable(True)
        self.action_best_fit.setChecked(False)
        self.action_best_fit.setEnabled(False)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/icons/best-fit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_best_fit.setIcon(icon20)
        self.action_best_fit.setVisible(True)
        self.action_best_fit.setObjectName("action_best_fit")
        self.action_save_image = QtWidgets.QAction(MainWindowView)
        self.action_save_image.setEnabled(True)
        self.action_save_image.setObjectName("action_save_image")
        self.action_open_file = QtWidgets.QAction(MainWindowView)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/icons/archive-extract.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open_file.setIcon(icon21)
        font = QtGui.QFont()
        self.action_open_file.setFont(font)
        self.action_open_file.setObjectName("action_open_file")
        self.actionRecent_file_1 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_file_1.setText("&recent_file_1")
        self.actionRecent_file_1.setIconText("recent_file_1")
        self.actionRecent_file_1.setToolTip("recent_file_1")
        self.actionRecent_file_1.setVisible(False)
        self.actionRecent_file_1.setObjectName("actionRecent_file_1")
        self.actionRecent_file_2 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_file_2.setText("recent_&file_2")
        self.actionRecent_file_2.setIconText("recent_file_2")
        self.actionRecent_file_2.setToolTip("recent_file_2")
        self.actionRecent_file_2.setVisible(False)
        self.actionRecent_file_2.setObjectName("actionRecent_file_2")
        self.actionRecent_file_3 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_file_3.setText("recent_file_&3")
        self.actionRecent_file_3.setIconText("recent_file_3")
        self.actionRecent_file_3.setToolTip("recent_file_3")
        self.actionRecent_file_3.setVisible(False)
        self.actionRecent_file_3.setObjectName("actionRecent_file_3")
        self.actionRecent_file_4 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_file_4.setText("recent_file_&4")
        self.actionRecent_file_4.setIconText("recent_file_4")
        self.actionRecent_file_4.setToolTip("recent_file_4")
        self.actionRecent_file_4.setVisible(False)
        self.actionRecent_file_4.setObjectName("actionRecent_file_4")
        self.actionRecent_file_5 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_file_5.setText("recent_file_&5")
        self.actionRecent_file_5.setIconText("recent_file_5")
        self.actionRecent_file_5.setToolTip("recent_file_5")
        self.actionRecent_file_5.setVisible(False)
        self.actionRecent_file_5.setObjectName("actionRecent_file_5")
        self.actionRecent_file_6 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_file_6.setText("recent_file_&6")
        self.actionRecent_file_6.setToolTip("recent_file_6")
        self.actionRecent_file_6.setVisible(False)
        self.actionRecent_file_6.setObjectName("actionRecent_file_6")
        self.actionRecent_file_7 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_file_7.setText("recent_file_&7")
        self.actionRecent_file_7.setIconText("recent_file_7")
        self.actionRecent_file_7.setToolTip("recent_file_7")
        self.actionRecent_file_7.setVisible(False)
        self.actionRecent_file_7.setObjectName("actionRecent_file_7")
        self.actionRecent_file_8 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_file_8.setText("recent_file_&8")
        self.actionRecent_file_8.setIconText("recent_file_8")
        self.actionRecent_file_8.setToolTip("recent_file_8")
        self.actionRecent_file_8.setVisible(False)
        self.actionRecent_file_8.setObjectName("actionRecent_file_8")
        self.actionRecent_file_9 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_file_9.setText("recent_file_&9")
        self.actionRecent_file_9.setIconText("recent_file_9")
        self.actionRecent_file_9.setToolTip("recent_file_9")
        self.actionRecent_file_9.setVisible(False)
        self.actionRecent_file_9.setObjectName("actionRecent_file_9")
        self.actionRecent_file_10 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_file_10.setText("recent_file_&10")
        self.actionRecent_file_10.setIconText("recent_file_10")
        self.actionRecent_file_10.setToolTip("recent_file_10")
        self.actionRecent_file_10.setVisible(False)
        self.actionRecent_file_10.setObjectName("actionRecent_file_10")
        self.actionRecent_bookmark_1 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_bookmark_1.setText("&recent_bookmark_1")
        self.actionRecent_bookmark_1.setIconText("recent_bookmark_1")
        self.actionRecent_bookmark_1.setToolTip("recent_bookmark_1")
        self.actionRecent_bookmark_1.setVisible(False)
        self.actionRecent_bookmark_1.setObjectName("actionRecent_bookmark_1")
        self.actionRecent_bookmark_2 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_bookmark_2.setText("recent_&bookmark_2")
        self.actionRecent_bookmark_2.setIconText("recent_bookmark_2")
        self.actionRecent_bookmark_2.setToolTip("recent_bookmark_2")
        self.actionRecent_bookmark_2.setVisible(False)
        self.actionRecent_bookmark_2.setObjectName("actionRecent_bookmark_2")
        self.actionRecent_bookmark_3 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_bookmark_3.setText("recent_bookmark_&3")
        self.actionRecent_bookmark_3.setIconText("recent_bookmark_3")
        self.actionRecent_bookmark_3.setToolTip("recent_bookmark_3")
        self.actionRecent_bookmark_3.setVisible(False)
        self.actionRecent_bookmark_3.setObjectName("actionRecent_bookmark_3")
        self.actionRecent_bookmark_4 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_bookmark_4.setText("recent_bookmark_&4")
        self.actionRecent_bookmark_4.setToolTip("recent_bookmark_4")
        self.actionRecent_bookmark_4.setVisible(False)
        self.actionRecent_bookmark_4.setObjectName("actionRecent_bookmark_4")
        self.actionRecent_bookmark_5 = QtWidgets.QAction(MainWindowView)
        self.actionRecent_bookmark_5.setText("recent_bookmark_&5")
        self.actionRecent_bookmark_5.setIconText("recent_bookmark_5")
        self.actionRecent_bookmark_5.setToolTip("recent_bookmark_5")
        self.actionRecent_bookmark_5.setVisible(False)
        self.actionRecent_bookmark_5.setObjectName("actionRecent_bookmark_5")
        self.action_en_us = QtWidgets.QAction(MainWindowView)
        self.action_en_us.setCheckable(True)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/famfamfam_flag_icons/png/us.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_en_us.setIcon(icon22)
        self.action_en_us.setObjectName("action_en_us")
        self.action_pt_br = QtWidgets.QAction(MainWindowView)
        self.action_pt_br.setCheckable(True)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/famfamfam_flag_icons/png/br.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_pt_br.setIcon(icon23)
        self.action_pt_br.setIconText("pt_BR")
        self.action_pt_br.setObjectName("action_pt_br")
        self.action_show_toolbar = QtWidgets.QAction(MainWindowView)
        self.action_show_toolbar.setCheckable(True)
        self.action_show_toolbar.setChecked(True)
        self.action_show_toolbar.setObjectName("action_show_toolbar")
        self.action_double_page_mode = QtWidgets.QAction(MainWindowView)
        self.action_double_page_mode.setCheckable(True)
        self.action_double_page_mode.setEnabled(False)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/icons/icons/distribute-horizontal-margin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_double_page_mode.setIcon(icon24)
        self.action_double_page_mode.setIconVisibleInMenu(True)
        self.action_double_page_mode.setObjectName("action_double_page_mode")
        self.action_manga_mode = QtWidgets.QAction(MainWindowView)
        self.action_manga_mode.setCheckable(True)
        self.action_manga_mode.setEnabled(False)
        self.action_manga_mode.setObjectName("action_manga_mode")
        self.menu_recent_files.addAction(self.actionRecent_file_1)
        self.menu_recent_files.addAction(self.actionRecent_file_2)
        self.menu_recent_files.addAction(self.actionRecent_file_3)
        self.menu_recent_files.addAction(self.actionRecent_file_4)
        self.menu_recent_files.addAction(self.actionRecent_file_5)
        self.menu_recent_files.addAction(self.actionRecent_file_6)
        self.menu_recent_files.addAction(self.actionRecent_file_7)
        self.menu_recent_files.addAction(self.actionRecent_file_8)
        self.menu_recent_files.addAction(self.actionRecent_file_9)
        self.menu_recent_files.addAction(self.actionRecent_file_10)
        self.menu_file.addAction(self.action_open_file)
        self.menu_file.addAction(self.action_open_folder)
        self.menu_file.addAction(self.menu_recent_files.menuAction())
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_save_image)
        self.menu_file.addSeparator()
        self.menu_file.addAction(self.action_exit)
        self.menu_view.addAction(self.action_fullscreen)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.action_original_fit)
        self.menu_view.addAction(self.action_vertical_fit)
        self.menu_view.addAction(self.action_horizontal_fit)
        self.menu_view.addAction(self.action_best_fit)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.action_rotate_left)
        self.menu_view.addAction(self.action_rotate_right)
        self.menu_view.addSeparator()
        self.menu_view.addAction(self.action_double_page_mode)
        self.menu_view.addAction(self.action_manga_mode)
        self.menu_navegation.addAction(self.action_next_page)
        self.menu_navegation.addAction(self.action_previous_page)
        self.menu_navegation.addSeparator()
        self.menu_navegation.addAction(self.action_first_page)
        self.menu_navegation.addAction(self.action_last_page)
        self.menu_navegation.addSeparator()
        self.menu_navegation.addAction(self.action_go_to_page)
        self.menu_navegation.addSeparator()
        self.menu_navegation.addAction(self.action_next_comic)
        self.menu_navegation.addAction(self.action_previous_comic)
        self.menu_help.addAction(self.action_about)
        self.menu_help.addAction(self.action_about_qt)
        self.menu_settings.addAction(self.action_show_toolbar)
        self.menu_settings.addAction(self.action_show_statusbar)
        self.menu_settings.addSeparator()
        self.menu_settings.addAction(self.action_preference_dialog)
        self.menu_recent_bookmarks.addAction(self.actionRecent_bookmark_1)
        self.menu_recent_bookmarks.addAction(self.actionRecent_bookmark_2)
        self.menu_recent_bookmarks.addAction(self.actionRecent_bookmark_3)
        self.menu_recent_bookmarks.addAction(self.actionRecent_bookmark_4)
        self.menu_recent_bookmarks.addAction(self.actionRecent_bookmark_5)
        self.menu_bookmarks.addAction(self.action_add_bookmark)
        self.menu_bookmarks.addAction(self.action_remove_bookmark)
        self.menu_bookmarks.addSeparator()
        self.menu_bookmarks.addAction(self.action_bookmark_manager)
        self.menu_bookmarks.addAction(self.menu_recent_bookmarks.menuAction())
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_navegation.menuAction())
        self.menubar.addAction(self.menu_bookmarks.menuAction())
        self.menubar.addAction(self.menu_settings.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.toolbar.addAction(self.action_open_file)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_previous_comic)
        self.toolbar.addAction(self.action_first_page)
        self.toolbar.addAction(self.action_previous_page)
        self.toolbar.addAction(self.action_next_page)
        self.toolbar.addAction(self.action_last_page)
        self.toolbar.addAction(self.action_next_comic)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_go_to_page)
        self.toolbar.addAction(self.action_add_bookmark)
        self.toolbar.addAction(self.action_remove_bookmark)
        self.toolbar.addAction(self.action_bookmark_manager)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_rotate_left)
        self.toolbar.addAction(self.action_rotate_right)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_original_fit)
        self.toolbar.addAction(self.action_vertical_fit)
        self.toolbar.addAction(self.action_horizontal_fit)
        self.toolbar.addAction(self.action_best_fit)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_fullscreen)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_double_page_mode)
        self.toolbar.addSeparator()
        self.toolbar.addAction(self.action_exit)

        self.retranslateUi(MainWindowView)
        QtCore.QMetaObject.connectSlotsByName(MainWindowView)

    def retranslateUi(self, MainWindowView):
        _translate = QtCore.QCoreApplication.translate
        MainWindowView.setWindowTitle(_translate("MainWindowView", "Pynocchio"))
        MainWindowView.setAccessibleName(_translate("MainWindowView", "Pynocchio"))
        MainWindowView.setAccessibleDescription(_translate("MainWindowView", "The Best Comic Reader"))
        self.menu_file.setTitle(_translate("MainWindowView", "&File"))
        self.menu_recent_files.setTitle(_translate("MainWindowView", "&Recent files"))
        self.menu_view.setTitle(_translate("MainWindowView", "&View"))
        self.menu_navegation.setTitle(_translate("MainWindowView", "&Navegation"))
        self.menu_help.setTitle(_translate("MainWindowView", "&Help"))
        self.menu_settings.setTitle(_translate("MainWindowView", "&Settings"))
        self.menu_bookmarks.setTitle(_translate("MainWindowView", "&Bookmarks"))
        self.menu_recent_bookmarks.setTitle(_translate("MainWindowView", "R&ecente bookmarks"))
        self.toolbar.setWindowTitle(_translate("MainWindowView", "toolBar"))
        self.action_about.setText(_translate("MainWindowView", "&About Pynocchio"))
        self.action_about_qt.setText(_translate("MainWindowView", "About &Qt"))
        self.action_exit.setText(_translate("MainWindowView", "&Exit"))
        self.action_exit.setShortcut(_translate("MainWindowView", "Ctrl+Q"))
        self.action_next_page.setText(_translate("MainWindowView", "&Next page"))
        self.action_next_page.setShortcut(_translate("MainWindowView", "Right"))
        self.action_previous_page.setText(_translate("MainWindowView", "&Previous page"))
        self.action_previous_page.setShortcut(_translate("MainWindowView", "Left"))
        self.action_first_page.setText(_translate("MainWindowView", "&First page"))
        self.action_first_page.setShortcut(_translate("MainWindowView", "Ctrl+Left"))
        self.action_last_page.setText(_translate("MainWindowView", "&Last page"))
        self.action_last_page.setShortcut(_translate("MainWindowView", "Ctrl+Right"))
        self.action_rotate_left.setText(_translate("MainWindowView", "&Rotate left"))
        self.action_rotate_left.setShortcut(_translate("MainWindowView", "Ctrl+Shift+R"))
        self.action_rotate_right.setText(_translate("MainWindowView", "Rotat&e right"))
        self.action_rotate_right.setShortcut(_translate("MainWindowView", "Ctrl+R"))
        self.action_horizontal_fit.setText(_translate("MainWindowView", "&Horizontal fit"))
        self.action_horizontal_fit.setShortcut(_translate("MainWindowView", "Ctrl+K"))
        self.action_fullscreen.setText(_translate("MainWindowView", "&Fullscreen"))
        self.action_fullscreen.setShortcut(_translate("MainWindowView", "F"))
        self.action_go_to_page.setText(_translate("MainWindowView", "&Go to page"))
        self.action_go_to_page.setShortcut(_translate("MainWindowView", "Ctrl+G"))
        self.action_original_fit.setText(_translate("MainWindowView", "&Original fit"))
        self.action_original_fit.setShortcut(_translate("MainWindowView", "Ctrl+H"))
        self.action_show_statusbar.setText(_translate("MainWindowView", "S&how Statusbar"))
        self.action_add_bookmark.setText(_translate("MainWindowView", "&Add bookmark"))
        self.action_remove_bookmark.setText(_translate("MainWindowView", "&Remove bookmark"))
        self.action_bookmark_manager.setText(_translate("MainWindowView", "&Bookmark manager"))
        self.action_open_folder.setText(_translate("MainWindowView", "Open &Folder"))
        self.action_next_comic.setText(_translate("MainWindowView", "Next &Comic"))
        self.action_next_comic.setShortcut(_translate("MainWindowView", "Ctrl+Shift+Right"))
        self.action_previous_comic.setText(_translate("MainWindowView", "P&revious Comic"))
        self.action_previous_comic.setShortcut(_translate("MainWindowView", "Ctrl+Shift+Left"))
        self.action_preference_dialog.setText(_translate("MainWindowView", "&Preferences"))
        self.action_vertical_fit.setText(_translate("MainWindowView", "&Vertical fit"))
        self.action_vertical_fit.setShortcut(_translate("MainWindowView", "Ctrl+J"))
        self.action_best_fit.setText(_translate("MainWindowView", "&Best fit"))
        self.action_best_fit.setShortcut(_translate("MainWindowView", "Ctrl+L"))
        self.action_save_image.setText(_translate("MainWindowView", "&Save image"))
        self.action_save_image.setWhatsThis(_translate("MainWindowView", "Save current image in disk."))
        self.action_save_image.setShortcut(_translate("MainWindowView", "Ctrl+S"))
        self.action_open_file.setText(_translate("MainWindowView", "&Open File"))
        self.action_open_file.setShortcut(_translate("MainWindowView", "Ctrl+O"))
        self.action_en_us.setText(_translate("MainWindowView", "English"))
        self.action_en_us.setIconText(_translate("MainWindowView", "en_US"))
        self.action_pt_br.setText(_translate("MainWindowView", "Portuguese"))
        self.action_show_toolbar.setText(_translate("MainWindowView", "&Show Toolbar"))
        self.action_double_page_mode.setText(_translate("MainWindowView", "&Double Page Mode"))
        self.action_double_page_mode.setToolTip(_translate("MainWindowView", "Active double page mode"))
        self.action_manga_mode.setText(_translate("MainWindowView", "&Manga Mode"))

from .custom_widgets.qscroll_area_viewer import QScrollAreaViewer
from .custom_widgets.status_bar import StatusBar
from . import main_window_view_rc
